name: Dev Flow - FinancialHub

on:
  push:
    branches:
      - develop
      - '**/dev'

jobs:
  acknowledge-push:
    name: Detecção de push em branches de desenvolvimento
    runs-on: self-hosted

    steps:
      - name: Runner ativo e evento detectado
        run: |
          echo "Branch recebida:"
          echo "${GITHUB_REF_NAME}"
